name: Java SDK Matrix CI

on:
  push:
    branches-ignore:
      - staging-test
  pull_request:

jobs:
  build:
    name: Test ${{ matrix.module }} on JDK ${{ matrix.java }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: ['8']
        module: [ 'core', 'http5' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}

      - name: Clean Gradle plugin cache
        run: |
          rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
          rm -fr $HOME/.gradle/caches/*/plugin-resolution/

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ matrix.java }}-${{ matrix.module }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create test subaccount
        run: ./gradlew createTestSubAccount -PmoduleName=${{ matrix.module }}

      - name: Load CLOUDINARY_URL and run ciTest
        run: |
          source tools/cloudinary_url.txt
          ./gradlew -DCLOUDINARY_URL=$CLOUDINARY_URL ciTest -p cloudinary-${{ matrix.module }} -i